INSERT INTO items (categories_id, name) VALUES
  (1, 'Inception'),
  (1, 'The Shawshank Redemption'),
  (1, 'Pulp Fiction'),
  (1, 'Dark Knight'),
  (1, 'Monty Python'),
  (2, 'Pizza Hut'),
  (2, 'Fancy McRestaurant'),
  (2, 'Sushi Sushi'),
  (3, 'The Mom Test'),
  (3, 'Harry Potter'),
  (3, 'Tress of the Emerald Sea'),
  (4, 'Guitar'),
  (4, 'PS5'),
  (4, 'YoYo'),
  (5, 'Japan'),
  (5, 'Calgary'),
  (5, 'Vancouver');
