INSERT INTO items (owner_id, categories_id, name) VALUES
  (1, 1, 'Inception'),
  (1, 1, 'The Shawshank Redemption'),
  (1, 1, 'Pulp Fiction'),
  (1, 2, 'Pizza Hut'),
  (2, 2, 'Sushi King'),
  (2, 2, 'Burger Queen'),
  (3, 3, 'To Kill a Mockingbird'),
  (3, 3, '1984'),
  (3, 3, 'The Great Gatsby'),
  (4, 4, 'Groceries'),
  (4, 4, 'Clothes'),
  (4, 4, 'Electronics'),
  (5, 1, 'The Matrix'),
  (5, 1, 'The Godfather'),
  (5, 1, 'The Dark Knight'),
  (6, 2, 'Sushi King'),
  (6, 2, 'Burger Queen'),
  (6, 2, 'Salad Masters'),
  (7, 3, 'Harry Potter and the Sorcerer''s Stone'),
  (7, 3, 'The Catcher in the Rye'),
  (7, 3, 'Moby-Dick'),
  (8, 4, 'Books'),
  (8, 4, 'Furniture'),
  (8, 4, 'Appliances'),
  (9, 1, 'Avatar'),
  (9, 1, 'The Lord of the Rings'),
  (9, 1, 'The Avengers'),
  (10, 1, 'Interstellar'),
  (10, 1, 'The Green Mile'),
  (10, 1, 'Fight Club');

